package com.charity.jointnewsletter.navigation

const val ROUTE_SPLASH = ""
const val ROUTE_HOME = "home"
const val ROUTE_REGISTER = "register"
const val ROUTE_LOGIN = "login"
const val ROUTE_CONTACT = "contact"
const val ROUTE_ONBOARDING = "onboarding"
const val ROUTE_SETTINGS = "settings"
const val ROUTE_ABOUT = "about"
const val ROUTE_POLICY = "privacy_policy"
const val ROUTE_FEEDBACK = "feedback"
const val ROUTE_TOPIC ="topics"
const val ROUTE_CATEGORY="categories"
const val ROUTE_ARTICLE_DETAILS="details"
