package com.charity.jointnewsletter.navigation

const val ROUTE_SPLASH = "splash"
const val ROUTE_HOME = "home"
const val ROUTE_REGISTER = "register"
const val ROUTE_LOGIN = "login"
const val ROUTE_CONTACT = "contact"
const val ROUTE_ONBOARDING = "onboarding"
const val ROUTE_SETTINGS = "settings"
const val ROUTE_ABOUT = "about"
const val ROUTE_POLICY = "privacy"
const val ROUTE_FEEDBACK = "feedback"
const val ROUTE_TOPICS ="topic"
const val ROUTE_CATEGORY="category"
const val ROUTE_ARTICLE_DETAILS="detail"
const val ROUTE_FLAGS = "flags"
const val ROUTE_POEMS = "poems"
const val ROUTE_GAMES = "games"
const val ROUTE_DISHES = "dishes"
const val ROUTE_NOTIFICATIONS="notifications"
